# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sealog Documentation
email: info@oceandatatools.org
description: >- # this means to ignore newlines until "baseurl:"
  Sealog is a general purpose event logging framework built to support research
  vessels and deployed underwater vehicles. It provides vessel/vehicle
  operators with an event-logging solution that can be customized to support
  the operator’s unique needs and provide a science party with a tool that
  allows them to design and enforce standardized documenting procedures and
  vocabularies.
# twitter_username: username
github_username: oceandatatools
minimal_mistakes_skin: default
search: true

# GitHub Pages integration
# domain: oceandatatools.github.icon
# baseurl: /sealog_docs/

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _docs

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - _docs/wip-*

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-toc

author:
#  name   : "First Lastname"
#  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Sealog is a general purpose event logging framework built to
    support research vessels and deployed underwater vehicles."
  # links:
  #   - label: "Website"
  #     icon: "fas fa-fw fa-link"
  #     url: "https://www.oceandatatools.org"
  #   - label: "GitHub"
  #     icon: "fab fa-fw fa-github"
  #     url: "https://github.com/OceanDataTools/sealog-server"

atom_feed:
  hide: true

footer:
  links:
    - label: "Website"
      icon: "fas fa-globe"
      url: "https://www.oceandatatools.org"
    - label: "GitHub Repositories"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/orgs/OceanDataTools/repositories?q=sealog"
    - label: "MIT Open Source License"
      icon: "fas fa-file-alt"
      url: "https://opensource.org/license/mit"

defaults:
  # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true

  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "navdocs"

  - scope:
      path: ""
      type: pages
    values:
      layout: home
      author_profile: true
      sidebar:
        nav: "navdocs"

  # _pages
  # - scope:
  #     path: "_pages"
  #     type: pages
  #   values:
  #     layout: single
  #     author_profile: true

#toc:
#  min_level: 1
#  max_level: 6
#  no_toc_section_class: "no_toc_section"
#  list_class: "toc-list"
#  sublist_class: "toc-sublist"
#  item_class: "toc-list-item"

toc: true
toc_label: "Table of Contents"
toc_icon: "cog"  # Choose an icon from FontAwesome (optional)
toc_levels: "1..4"  # Define which heading levels to include in the TOC

############################
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  docs:
    output: true
    permalink: /:collection/:name
